### ISSUE TITLE
Cannot run dashboard npm start error

### ISSUE THREAD

**Issue by timreachmaine** [itemsapi/dashboard#13]
Running ElasticSearch 2.4
Ubuntu 16.04.1 LTS
Nodejs 4.5.0
![documents-folder](https://cloud.githubusercontent.com/assets/22325524/18694155/d12dd238-7f75-11e6-9358-10662e3d3f48.png)
![itemsapi-folder](https://cloud.githubusercontent.com/assets/22325524/18694156/d1612e8a-7f75-11e6-873e-f0d69b95e759.png)
[nodeapp.jserror.txt](https://github.com/itemsapi/dashboard/files/483904/nodeapp.jserror.txt)
[npminstallerror.txt](https://github.com/itemsapi/dashboard/files/483905/npminstallerror.txt)
[npminstallproductionerror.txt](https://github.com/itemsapi/dashboard/files/483906/npminstallproductionerror.txt)

As I mentioned, I installed the Dashboard from GIT AFTER installing the backend. I cannot seem to resolve the CRUD backend either. Thanks for any help. I hope to develop a regional search hub for autos, real estate, jobs, business directory and news search for a regional publisher with this potentially awesome platform.

**Comment by timreachmaine** [comment]
Just noticed that after running "node app.js" in terminal....after a long delay, I get a response of "TypeError: Cannot read property 'project' of undefined.

Unhandled rejection Error: [index_not_found_exception] no such index, with: {"resource.type":"index_or_alias","resource.id":"project","index":"project"}
    at respond (/home/tim/Documents/node_modules/elasticsearch/src/lib/transport.js:256:15)
    at checkRespForFailure (/home/tim/Documents/node_modules/elasticsearch/src/lib/transport.js:219:7)
    at HttpConnector.<anonymous> (/home/tim/Documents/node_modules/elasticsearch/src/lib/connectors/http.js:155:7)
    at IncomingMessage.wrapper (/home/tim/Documents/node_modules/lodash/index.js:3095:19)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
Unhandled rejection Error: [index_not_found_exception] no such index, with: {"resource.type":"index_or_alias","resource.id":"project","index":"project"}
    at respond (/home/tim/Documents/node_modules/elasticsearch/src/lib/transport.js:256:15)
    at checkRespForFailure (/home/tim/Documents/node_modules/elasticsearch/src/lib/transport.js:219:7)
    at HttpConnector.<anonymous> (/home/tim/Documents/node_modules/elasticsearch/src/lib/connectors/http.js:155:7)
    at IncomingMessage.wrapper (/home/tim/Documents/node_modules/lodash/index.js:3095:19)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
Unhandled rejection Error: [index_not_found_exception] no such index, with: {"resource.type":"index_or_alias","resource.id":"project","index":"project"}
    at respond (/home/tim/Documents/node_modules/elasticsearch/src/lib/transport.js:256:15)
    at checkRespForFailure (/home/tim/Documents/node_modules/elasticsearch/src/lib/transport.js:219:7)
    at HttpConnector.<anonymous> (/home/tim/Documents/node_modules/elasticsearch/src/lib/connectors/http.js:155:7)
    at IncomingMessage.wrapper (/home/tim/Documents/node_modules/lodash/index.js:3095:19)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
[TypeError: Cannot read property 'project' of undefined]
[TypeError: Cannot read property 'project' of undefined]
[TypeError: Cannot read property 'project' of undefined]

**Comment by cigolpl** [comment]
Hey @timreachmaine,

Thanks for providing more details. "regional search hub for autos, real estate, jobs, business directory and news search" that's great use case.

In terms of bugs I've tested that on digitalocean.com with ubuntu 14.04 and 16.04. Actually I had similar problem once using the latest npm. Once I downgraded it to npm 3.8.6 everything was fine.

I recommend you to look at https://github.com/itemsapi/dashboard/blob/master/TROUBLESHOOTING.md. I've addressed your issues there and hope it will be helpful. 

I recommend also starting with `PORT=3000 npm start` instead of `node app.js`

In terms of second error, that's weird, it can be caused by the newest version of Elasticsearch 2.4. I am using mostly Elasticsearch 1.7. Hope I'll debug that someday.

I've tested also dashboard now with heroku and everything is fine and even importing example data (https://raw.githubusercontent.com/itemsapi/itemsapi-example-data/master/items/restaurants.json) by form works very well out of the box 

Let me know if that helped you fix problem, if not we could try another methods.
